return {
  { "tiagovla/tokyodark.nvim", lazy = true },
  { "rebelot/kanagawa.nvim" },
  { "catppuccin/nvim", lazy = true },
  { "EdenEast/nightfox.nvim", lazy = true },
  { "Mofiqul/vscode.nvim", lazy = true },
  { "Mofiqul/dracula.nvim", lazy = true },
  { "scottmckendry/cyberdream.nvim", lazy = true },
  { "ellisonleao/gruvbox.nvim", lazy = true },
  { "nyoom-engineering/oxocarbon.nvim", lazy = true },
  { "loctvl842/monokai-pro.nvim", lazy = true },
  { "sainnhe/sonokai", lazy = true },
  { "rose-pine/neovim", lazy = true },
  { "olimorris/onedarkpro.nvim", lazy = true },
  { "luisiacc/gruvbox-baby", lazy = true },
  { "sainnhe/everforest", lazy = true },
  { "kdheepak/monochrome.nvim", lazy = true },
  { "craftzdog/solarized-osaka.nvim", lazy = true },
  { "projekt0n/github-nvim-theme", lazy = true },
  { "marko-cerovac/material.nvim", lazy = true },
  { "ribru17/bamboo.nvim", lazy = true },
  { "maxmx03/solarized.nvim", lazy = true },
  { "bluz71/vim-moonfly-colors", lazy = true },
  { "vague2k/vague.nvim", lazy = true },
}
